version: '3.8'
services:
  db:
    image: 'thiagodiasdev/cartao-fiap-db:latest'
    build:
      context: .
      dockerfile: ./mysql-server.dockerfile
    deploy:
      replicas: 1
    ports:
      - '3036:3036'
  api:
    image: 'compra:latest'
    ports:
      - '8084:8084'
    deploy:
      replicas: 2