# version: "3.0"

# services:
#   compra:
#     image: compra:1.0
#     ports:
#       - "8084:8084"
#     networks:
#       - fiap_cred_overlay_net
#     deploy:
#       replicas: 2

#   db:
#     image: thiagodiasdev/cartao-fiap-db:latest
#     networks:
#       - fiap_cred_overlay_net
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_ROOT_PASSWORD=123456
#       - MYSQL_USER=root
#       - MYSQL_DATABASE=db_fiap_cartao
#     deploy:
#       replicas: 1

# networks:
#   fiap_cred_overlay_net:
#     driver: overlay
version: '3'
services:
    #compra:
    #    image: compra:1.0
    #    ports:
    #    - 8084:8084
    #    deploy:
    #        replicas: 2
    db:
        image: thiagodiasdev/cartao-fiap-db:latest
        build: 
            context: .
            dockerfile: ./mysql-server.dockerfile
        ports:
            - 3306:3306
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                max_attempts: 3
        networks:
            - net
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: db_fiap_cartao
networks:
    net:
        driver: overlay