server:
  port: '8084'

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/db_fiap_cartao?serverTimezone=UTC
    password: '123456'
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: update
        format_sql: 'true'
        id:
          new_generator_mappings: 'true'
        show_sql: 'false'
    hibernate:
      ddl-auto: update
